global:
  scrape_interval: 5s  # 5秒ごとにメトリクスを収集

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['node:3000']  # Node.jsのコンテナ

  - job_name: 'mysql_node_metrics'
    static_configs:
      - targets: ['metrics-node:9104']
